version: '3.4'

networks:
  docker.network:
    driver: bridge

services:
  downloader:
    image: smart-downloader

postgres:
  image: postgres:17-alpine
  container_name: postgres-db
  restart: unless-stopped
  tty: true
  environment:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgresuser
    POSTGRES_PASSWORD: somepassword
  ports:
    - "5432:5442"
  networks:
    - docker.network
  volumes:
    - "./docker/postgres/dbdata:/var/lib/postgresql/data"
